### ISSUE TITLE
Server calls a render method.

### ISSUE THREAD

**Issue by VoilaTada** [xy-project/Project-XY#3]
When in a pack that includes Extra Utilities, your code calls a rendering method, even for the server installation of the mod. Here's the portion of the server log that seems relevant. http://pastebin.com/LK6ZdkDC

**Comment by xy-project** [comment]
If I were to call it on my own mod, I would know the issue. Also, the crash happens during ExtraUtilities post initialization, so it's not my fault (I don't think), refer Tema to this issue when you create an issue on the ExtraUtilities issue page. The reason why I'm (mostly) sure it's Tema's fault is because I don't have access to his code, so I can't provide you the answer.

**Comment by xy-project** [comment]
I can't reproduce the issue, same version of EU, and the latest version of ProjectXY. Nigher it is my fault. Tema regardless refused to look at the issue because of the description I provided beforehand. Because I said that the client only calls getRenderType, I was wrong, doesn't mean the issue is still my fault.

**Comment by xy-project** [comment]
Doing some more investigation, found out it was a derpy Scala thing. Basically once it calls anything an object, which I use to hold the render type, it initiated other fields, which some of them be client side only. The issue will be fixed in the next release, expect it to be coming soon.

**Comment by Ommina** [comment]
This issue persists in 0.2.0-pre (Aug 24) and EU 1.2.11.

Should I create a new issue for this, or am I simply not being patient enough for the update with the fix to be released?  (Apologies if so!)

http://pastebin.com/EPA02khf

**Comment by xy-project** [comment]
It should be fixed. If it still persists for other people I need a log. Your pastebin got removed.
